[package]
name = "loki"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "*"
yara = "*"
walkdir = "2"
rustop = "*"
arrayvec = "*"
simple_logger = "3.0.0"
