name: LOKI2 Build macOS

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Dependencies
      run: | 
        brew install autoconf automake libtool make gcc pkg-config
        brew install pkg-config

    - name: Install OpenSSL Dev
      run: |
        brew install openssl@1.1
        mkdir -p /usr/local/opt
        ln -s /opt/homebrew/opt/openssl\@1.1 /usr/local/opt/openssl

    - name: Install YARA
      run: |
        git clone https://github.com/VirusTotal/yara.git
        cd yara
        ./bootstrap.sh
        ./configure --with-crypto
        make
        sudo make install
    
    - name: Build
      run: cargo build --verbose

    #- name: Run tests
    #  run: cargo test --verbose
